openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/userInfo/:
    get:
      operationId: listUserInfos
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserInfo'
          description: ''
      tags:
      - api
    post:
      operationId: createUserInfo
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInfo'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserInfo'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserInfo'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
          description: ''
      tags:
      - api
  /api/userInfo/{id}/:
    get:
      operationId: retrieveUserInfo
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this user info.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
          description: ''
      tags:
      - api
    put:
      operationId: updateUserInfo
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this user info.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInfo'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserInfo'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserInfo'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateUserInfo
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this user info.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInfo'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserInfo'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserInfo'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyUserInfo
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this user info.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
components:
  schemas:
    UserInfo:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user_name:
          type: string
          maxLength: 32
        birth_day:
          type: string
          format: date
        age:
          type: integer
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - user_name
      - birth_day
